// Code generated by mockgen. DO NOT EDIT.
// Source: generation.go
// Package: mocks

package mocks

import (
	"context"
	"reflect"

	"nova-canvas/backend/internal/api/v1"
	"nova-canvas/backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerationService is a mock of GenerationService interface.
type MockGenerationService struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationServiceMockRecorder
}

// MockGenerationServiceMockRecorder is the mock recorder for MockGenerationService.
type MockGenerationServiceMockRecorder struct {
	mock *MockGenerationService
}

// NewMockGenerationService creates a new mock instance.
func NewMockGenerationService(ctrl *gomock.Controller) *MockGenerationService {
	mock := &MockGenerationService{ctrl: ctrl}
	mock.recorder = &MockGenerationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationService) EXPECT() *MockGenerationServiceMockRecorder {
	return m.recorder
}

// CreateGeneration mocks base method.
func (m *MockGenerationService) CreateGeneration(ctx context.Context, userID uint64, req *v1.CreateGenerationRequest) (*v1.CreateGenerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGeneration", ctx, userID, req)
	ret0, _ := ret[0].(*v1.CreateGenerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGeneration indicates an expected call of CreateGeneration.
func (mr *MockGenerationServiceMockRecorder) CreateGeneration(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGeneration", reflect.TypeOf((*MockGenerationService)(nil).CreateGeneration), ctx, userID, req)
}

// GetGeneration mocks base method.
func (m *MockGenerationService) GetGeneration(ctx context.Context, userID uint64, taskID string) (*v1.GetGenerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneration", ctx, userID, taskID)
	ret0, _ := ret[0].(*v1.GetGenerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneration indicates an expected call of GetGeneration.
func (mr *MockGenerationServiceMockRecorder) GetGeneration(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneration", reflect.TypeOf((*MockGenerationService)(nil).GetGeneration), ctx, userID, taskID)
}

// ListGenerations mocks base method.
func (m *MockGenerationService) ListGenerations(ctx context.Context, userID uint64, req *v1.ListGenerationsRequest) (*v1.ListGenerationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenerations", ctx, userID, req)
	ret0, _ := ret[0].(*v1.ListGenerationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenerations indicates an expected call of ListGenerations.
func (mr *MockGenerationServiceMockRecorder) ListGenerations(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenerations", reflect.TypeOf((*MockGenerationService)(nil).ListGenerations), ctx, userID, req)
}

// CancelGeneration mocks base method.
func (m *MockGenerationService) CancelGeneration(ctx context.Context, userID uint64, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelGeneration", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelGeneration indicates an expected call of CancelGeneration.
func (mr *MockGenerationServiceMockRecorder) CancelGeneration(ctx, userID, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelGeneration", reflect.TypeOf((*MockGenerationService)(nil).CancelGeneration), ctx, userID, taskID)
}